#!/usr/bin/env bash
set -euo pipefail

apt-get update -y
DEBIAN_FRONTEND=noninteractive apt-get install -y bind9 git

# /etc/bind/named.conf.options (как на скрине)
install -m 0644 /dev/null /etc/bind/named.conf.options
cat > /etc/bind/named.conf.options <<'EOF'
options {
        directory "/var/cache/bind";

        allow-query { any; };

        forwarders {
                8.8.8.8;
        };

        dnssec-validation no;

        listen-on-v6 port 53 { none; };
        listen-on port 53 { 127.0.0.1; 192.168.100.0/27; 192.168.100.32/28; 192.168.200.0/28; };
};
EOF

# /etc/bind/named.conf.local (как на скрине)
install -m 0644 /dev/null /etc/bind/named.conf.local
cat > /etc/bind/named.conf.local <<'EOF'
zone "au-team.irpo" {
        type master;
        file "master/au-team.db";
};

zone "100.168.192.in-addr.arpa" {
        type master;
        file "master/au-team_rev.db";
};
EOF

# Проверка конфигов (как в модуле)
named-checkconf

# Папка для зон
install -d -m 0755 /etc/bind/zones

# Клонируем репозиторий с шаблонами (как в модуле)
if [ ! -d /root/db-bind/.git ]; then
  rm -rf /root/db-bind
  git clone https://github.com/zalisfer/db-bind /root/db-bind
fi

# Копируем шаблоны
cp -f /root/db-bind/db.local /etc/bind/zones/au-team.db
cp -f /root/db-bind/db.127 /etc/bind/zones/au-team_rev.db

# Прямая зона (как на скрине)
install -m 0644 /dev/null /etc/bind/zones/au-team.db
cat > /etc/bind/zones/au-team.db <<'EOF'
;
; BIND data file for local loopback interface
;
$TTL    604800
@       IN      SOA     localhost. root.localhost. (
                              2         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
@       IN      NS      au-team.irpo.
@       IN      A       192.168.100.2
hq-rtr  IN      A       192.168.100.1
br-rtr  IN      A       192.168.200.1
hq-srv  IN      A       192.168.100.2
hq-cli  IN      A       192.168.100.35
br-srv  IN      A       192.168.200.2
moodle  IN      CNAME   hq-rtr.au-team.irpo.
wiki    IN      CNAME   hq-rtr.au-team.irpo.
EOF

# Обратная зона (как на скрине)
install -m 0644 /dev/null /etc/bind/zones/au-team_rev.db
cat > /etc/bind/zones/au-team_rev.db <<'EOF'
;
; BIND reverse data file for local loopback interface
;
$TTL    604800
@       IN      SOA     localhost. root.localhost. (
                              1         ; Serial
                         604800         ; Refresh
                          86400         ; Retry
                        2419200         ; Expire
                         604800 )       ; Negative Cache TTL
;
@       IN      NS      au-team.irpo.
1       IN      PTR     hq-rtr.au-team.irpo.
2       IN      PTR     hq-srv.au-team.irpo.
66      IN      PTR     hq-cli.au-team.irpo.
EOF

# Владелец и права (как в модуле)
chown -R root /etc/bind/zones
chmod 0640 /etc/bind/zones/*

# Папка master и копирование зон (как в модуле)
install -d -m 0755 /var/cache/bind/master
cp -f /etc/bind/zones/au-team.db /var/cache/bind/master/au-team.db
cp -f /etc/bind/zones/au-team_rev.db /var/cache/bind/master/au-team_rev.db

# Проверка с зонами (как в модуле)
named-checkconf -z

# resolv.conf на HQ-SRV (как на скрине)
install -m 0644 /dev/null /etc/resolv.conf
cat > /etc/resolv.conf <<'EOF'
# Generated by NetworkManager
nameserver 192.168.100.2
EOF

# Перезапуск BIND9 (как в модуле)
systemctl restart bind9
